# Dev servers start at 8090
server.port=8091

# DB Stuffs #
spring.datasource.url=jdbc:postgresql://localhost:5432/condors-dev
spring.datasource.hikari.maximum-pool-size=10

# Redis Stuffs #
spring.redis.host=127.0.0.1
spring.redis.port=6380

condors.trading.live=false
condors.trading.use.tws.api=false
condors.trading.api.host=localhost

condors.prices.first.ticker.id=9000001
condors.trading.base.tws.client.id=1005
condors.prices.max.tickers=3